### ISSUE TITLE
ValueError: I/O operation on uninitialized object

### ISSUE THREAD

**Issue by jiangweiatgithub** [rsennrich/Bleualign#26] opened 2018-04-20 11:50 UTC
Hi,

Can you please check this error? If you need the files to reproduce the issue, please let me know.

Thanks,
Wei

E:\repos\Bleualign>python  ./bleualign.py -s my_example\e.txt.seg -t my_example\c.txt.seg --srctotarget my_example\e.mt_zh-cn.txt.seg -o my_example\tm.txt
Process Process-6:
Traceback (most recent call last):
  File "D:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "E:\repos\Bleualign\bleualign\align.py", line 67, in tasks_producer
    for i,task in enumerate(collect_article(*data)):
  File "E:\repos\Bleualign\bleualign\align.py", line 38, in collect_article
    for line in text:
ValueError: I/O operation on uninitialized object

**Comment by rsennrich** [comment] 2018-04-23 12:39
thanks for reporting this error. If you can please share the files to reproduce this issue, this would be very helpful.

**Comment by jiangweiatgithub** [comment] 2018-04-23 14:57
Sure - you can download the package from OneDrive:
https://1drv.ms/f/s!AqMx36ZH6wJMg_UjqmVNUFpaOyaDWg

BTW, I have particular question - does this tool support files with some sentences in different order?

**Comment by rsennrich** [comment] 2018-04-24 08:55
the folder appears to be empty.

Bleualign will produce a monotonic sentence alignment. Sentences may be dropped (left unaligned) or merged, but no sentences will be reordered.

**Comment by jiangweiatgithub** [comment] 2018-04-24 09:00
Now the package is there!

**Comment by jiangweiatgithub** [comment] 2018-08-20 00:46
FYI, I have finally succeeded in Cygwin64. Now I guess that issues was due to the different slash/backslash conventions between Windows and *nix.

**Comment by rsennrich** [comment] 2018-08-20 10:58
thanks for the report. Can you clarify if you needed to change any code in Bleualign, or just the command line arguments? I don't think there's currently any Unix-specific paths in the code.

**Comment by jiangweiatgithub** [comment] 2018-08-20 11:00
I did not change anything - I just ran into a Cygwin64 bash prompt, and executed that command line of mine.

**Closed** 2018-08-20 12:43 UTC

**Comment by alexkillen** [comment] 2019-02-22 14:34
Just to add to this, I also get the same error when running on Windows. It appears to be caused by the different way that multiprocessing works on Windows. The easy fix is to disable multiprocessing for Windows platforms which you can do using platform.system().

I got this to work by changing bleualign/align.py so that the check for the Python version at the top of the file also checks for the platform, as shown below:

```python
import platform

if sys.version_info >= (2,6) and platform.system() != "Windows":
  import multiprocessing
  multiprocessing_enabled = 1
  number_of_threads = 4
else:
  multiprocessing_enabled = 0
```

There's also a nice side-effect in that platform.system() returns a different value for Cygwin, so if you use that multiprocessing will remain enabled, which works in Cygwin as @jiangweiatgithub mentioned.
