### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by echan00** [rsennrich/Bleualign#34] opened 2019-02-12 07:03 UTC
I am getting the error below when running bleualign. Is this a problem relating to python2 and python3?

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/T2T_Model/bleualign/bleualign/align.py", line 67, in tasks_producer
    for i,task in enumerate(collect_article(*data)):
  File "/root/T2T_Model/bleualign/bleualign/align.py", line 38, in collect_article
    for line in text:
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 369: invalid continuation byte
```

**Comment by rsennrich** [comment] 2019-02-12 13:10
can you give more details how you call Bleualign? There can be bugs related to encoding that are only triggered in specific settings, and I can't reproduce your problem right now. (These calls work for both python2 and python3, and give the same results):
```
python bleualign.py --source eval/eval1989.de --target eval/eval1989.fr --srctotarget eval/eval1989.google.fr --printempty --out tmp1

python3 bleualign.py --source eval/eval1989.de --target eval/eval1989.fr --srctotarget eval/eval1989.google.fr --printempty --out tmp2
```

**Comment by echan00** [comment] 2019-02-12 14:51
From my limited knowledge based on the links below, it looks like in python3 it is necessary to define the file encoding (which defaults to UTF-8) when it is read and cannot mix bytes and unicode. This doesn't seem to be a problem with python2.


https://stackoverflow.com/questions/23917729/switching-to-python-3-causing-unicodedecodeerror
https://wiki.python.org/moin/Python3UnicodeDecodeError

**Comment by rsennrich** [comment] 2019-02-12 17:29
from the python3 io doc:

> In text mode, if encoding is not specified the encoding used is platform
    dependent: locale.getpreferredencoding(False) is called to get the
    current locale encoding. 

I'll make a note to switch this to UTF-8 encoding, but it will take some testing that this doesn't break anything for different versions and ways of calling bleualign.

**Comment by echan00** [comment] 2019-02-13 01:54
I would be happy to test if you send me the changes

**Comment by rsennrich** [comment] 2019-02-13 12:26
the latest commit opens files in UTF-8, but some other usage modes may still be broken (passing the files as file objects, or the content as strings).

can you please test this as follows?

```
python3 setup.py test
```

This currently succeeds in python2, and throws one error in python3 (because of a difference in the behavior of GaleChurch, which I couldn't look into yet).

**Comment by rsennrich** [comment] 2019-09-22 08:57
closing this since no more errors have been reported

**Closed by rsennrich** 2019-09-22 08:57 UTC
