### ISSUE TITLE
the aligner could use the same sentence multiple times in the output alignments

### ISSUE THREAD

**Issue by wangpd** [rsennrich/Bleualign#23] opened 2017-01-20 03:16 UTC
I found one weird example:
Input target text file is:

> A
> B

while the output alignment of the target side is:

> A
> A B

**Comment by rsennrich** [comment] 2017-01-20 15:09
Hello Pidong,

can you please provide a minimal reproducible example for this bug report?

thank you and best wishes,
Rico

**Comment by rsennrich** [comment] 2019-03-29 14:54
closing this due to lack of reproducible example.

**Closed by rsennrich** 2019-03-29 14:54 UTC
